server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotels/**

        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

